### ISSUE TITLE
Evaluation of MNIST with cacOpenset

### ISSUE THREAD

**Issue by tobokoch** [dimitymiller/cac-openset#10]
Hi,

thank you for providing the code of your paper!

I am running into a problem with the evaluation of MNIST with the CAC open-set model (script eval_cacOpenset.py). I am using the provided weights and trials 0-2 work fine, but trials 3 and 4 generate NaNs during the anchor mean computation. The problem here is that for some classes there are no correct predictions and therefore no anchor can be computed for that class. I suspect that there might be something wrong with the uploaded weights or how do you deal with this?

Thank you for your time and best regards!

**Comment by dimitymiller** [comment]
Hi @tobokoch 

Is this when using the provided pre-trained models? As flagged in the readme, the pre-trained models are now out-dated as they were for the old trial splits. During an update of the paper we moved to new trial splits to match other works -- I don't know why I didn't upload these new pre-trained models, likely issues with github storage. Sorry for the inconvenience.

You should be able to train models for the existing trial splits and then evaluate to reproduce the results. If this is not possible on your machine, let me know and i can quickly train on mine and send a google drive link.
