### ISSUE TITLE
where is the threshold？

### ISSUE THREAD

**Issue by dengwanxia1991** [dimitymiller/cac-openset#11]
Thank you for the contribution.

There is an issue. Where is the threshold theta to define the unknown classes? I can't find it.

**Comment by dimitymiller** [comment]
Hi dengwanxia1991

We don't define a threshold theta to identify unknown classes in this paper. The metrics (AUROC and CCR) used in this benchmark implicitly test across a range of thresholds to assess the ability of the uncertainty metric to separate known and unknown class examples.
