### ISSUE TITLE
anchor means are nan's

### ISSUE THREAD

**Issue by sesmae** [dimitymiller/cac-openset#3]
Hi,

Thank you for sharing your code. I tried to do an experiment with 80known-20unknown split on cifar100. I modified the dataloaders and config file respectively. The train_cacOpenset.py script trains the network. But when I run the evaluation script to get AUC , I get a bunch of 'nan's for  anchor_means. Do you have any idea what might be the reason?

**Comment by dimitymiller** [comment]
Hi @sesmae,

Seems like you've resolved this but my guess would have been that the anchor_means were being calculated without any correct training examples or that there was an issue with the network you trained where some training examples were nan's.

**Comment by sesmae** [comment]
Yes, there was a problem with my data splits. After fixing it , it worked.
Thank you for the clarification.
