### ISSUE TITLE
Question about Table 4

### ISSUE THREAD

**Issue by fuyimin96** [dimitymiller/cac-openset#8]
As you show Comparison with Existing Distance Losses in Table4, the result is different of CAC in table1
What is the backbone you use here for this Ablation Study

**Comment by dimitymiller** [comment]
It's the same backbone, just different splits of known/unknown classes. Table 4 was generated with random splits of known/unknown classes. Table 1 was regenerated to match the exact same split of known/unknown classes used by [13] for fair comparison with all other methods. The different splits didn't change our results dramatically, but there has been reports of it having a large impact on results of other methods.
